### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by FilipZamec** [silexlabs/grapesjs-symbols#10]
Hi,
just tried your demo and I also included plugin in my project and in both instances it throws error on this line: Object.defineProperty(exports, "__esModule", { value: true });
and saying exports is not defined.
And I can't see any symbols.

You can use your demo site.
Tested on Chrome.

Filip

**Comment by lexoyo** [comment]
oh no, i broke everything in the latest release
and the tests didn't break... i'm investigating now

**Comment by lexoyo** [comment]
fixed by https://github.com/silexlabs/grapesjs-symbols/commit/cb8b3cb33c5d709d9c9e97bcf8e5a8849e997eb1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by lexoyo** [comment]
thank you for reporting this

**Comment by FilipZamec** [comment]
Thank you for the fast fix 👍

**Comment by lexoyo** [comment]
I'm happy if somone else uses it and help me debug it

It is used in Silex too
