### ISSUE TITLE
Question: How can I dismiss a link between two instances?

### ISSUE THREAD

**Issue by FilipZamec** [silexlabs/grapesjs-symbols#11]
Hi,
In features it is written that I can: Unlink an instance so that it stops syncing

How do I do that? I found, that I can delete symbol in the settings of the instace, but it deletes the symbol completely. 
I want to keep the symbol for the future, but not for this instance.

Is it possible?

Thanks, Filip

**Comment by FilipZamec** [comment]
Because this way, I can create my custom blocks easilly, and if I want to change one, no problem :)

**Comment by lexoyo** [comment]
Yes it is implemented

You are right it is not visible in the demo, but it is in [Silex](https://v3.silex.me)

![Screenshot from 2023-11-09 17-16-33](https://github.com/silexlabs/grapesjs-symbols/assets/715377/63c674a0-4cd8-4dc6-927f-1c3978470188)

I don't see why it is not present in the demo, I see the trait in the DOM but it is empty, so there is [something wrong here](https://github.com/silexlabs/grapesjs-symbols/blob/4f35c3e5d2f378cb2cc3ff64d68d8c56383303c1/src/view/traits.ts#L31) I guess

Let me check it out as soon as I can

**Comment by lexoyo** [comment]
fixed, thank you for the bug report!

**Comment by lexoyo** [comment]
It looks like this on the preview now:

![Screenshot from 2023-11-10 11-49-07](https://github.com/silexlabs/grapesjs-symbols/assets/715377/37b567d8-61dd-4c93-9dd4-2567a0a356d6)

**Comment by FilipZamec** [comment]
It works, thank you.
Very useful plugin btw 👌

Thanks.
