### ISSUE TITLE
Plugin Installation, not detected

### ISSUE THREAD

**Issue by LienanWisner** [silexlabs/grapesjs-symbols#12]
Hi there! I want to install this plugin, but it says on console that it doesnt find it. Here's the message i get:

Plugin @silexlabs/grapesjs-symbols not found {context: 'plugins', plugin: '@silexlabs/grapesjs-symbols', level: 'warning'}context: "plugins"level: "warning"plugin: "@silexlabs/grapesjs-symbols"

Here is how I install my plugins:

plugins: [ plugin, stepper,  customSelect, fontSelect, '@silexlabs/grapesjs-symbols'],
    pluginsOpts: {
      '@silexlabs/grapesjs-symbols': {
          appendTo: '.gjs-pn-views-container',
        },
    }
    
    Am I doing something wrong or missing something?
    
    I did installed by npm i, but never imported, just what you see above. Thanks!

**Comment by lexoyo** [comment]
Hello
You need to import the plugin 
Maybe try with the CDN version First

**Comment by LienanWisner** [comment]
I've been having some problems with plugins and imports, I think its because the name, most of them are like:

import plugin from "..."

But I solved it with CDN, thank you, its working now!
