### ISSUE TITLE
Symbols wording / UI

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/grapesjs-symbols#4]
thx @ceubri to have reported this

The term symbol makes it look like if you delete a symbol, all its instances will be removed from the stage 

* [x] maybe document this: a symbol is the link between the instances, it listens to the change event and syncs all instances + keeps a copy internally for when the user wants to create a new instance
* [x] do not write "delete" symbols but "unlink" ?

**Comment by lexoyo** [comment]
What do you think of this one @Samkanda ?

**Comment by GetLikha** [comment]
For me I was thinking:

**Unlinking this symbol won't delete instances, just disconnects them.**

_Confirm to proceed or cancel to maintain the current link._

☐ Remind me again in the future 

[Unlink] [Cancel]

The remind me again in the future is important so it won't be repetitive and can help speed up the workflow

**Comment by lexoyo** [comment]
Sounds good ! @GetLikha

**Comment by lexoyo** [comment]
I implemented that @GetLikha :fire:
